networks:
  giteanet:
    external: false
  jenkinsnet:
    external: false
  gitjenkinsnet:
    external: false
  nginxnet:
    external: false

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - gitea
      - jenkins
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "3m"
    restart: always
    networks:
      - nginxnet
    ports:
      - 80:80
      - 222:222

  giteadb:
    image: postgres:16.4-alpine3.20
    container_name: giteadb
    environment:
      POSTGRES_DB: giteadb
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "3m"
    restart: always
    networks:
      - giteanet
    volumes:
      - ./data/giteadb-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # gitea:
  #   image: gitea/gitea:latest
  #   container_name: gitea
  #   environment:
  #     - GITEA__database__DB_TYPE=postgres
  #     - GITEA__database__HOST=giteadb:5432
  #     - GITEA__database__NAME=giteadb
  #     - GITEA__database__USER=gitea
  #     - GITEA__database__PASSWD=gitea
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-file: "2"
  #       max-size: "3m"
  #   restart: always
  #   depends_on:
  #     - giteadb
  #   networks:
  #     - giteanet
  #   links:
  #     - "giteadb"
  #   volumes:
  #     - ./Gitea/gitea-data:/data/
  #     - ./Gitea/app.ini:/data/gitea/conf/app.ini
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

  # https://www.technicalife.net/hello-forgejo-with-docker/
  gitea:
    image: codeberg.org/forgejo/forgejo:8.0.3
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=giteadb:5432
      - FORGEJO__database__NAME=giteadb
      - FORGEJO__database__USER=gitea
      - FORGEJO__database__PASSWD=gitea
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "3m"
    restart: always
    depends_on:
      - giteadb
    networks:
      - giteanet
      - gitjenkinsnet
      - nginxnet
    links:
      - "giteadb"
    volumes:
      - ./data/gitea-data:/data/
      - ./docker/gitea/app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '1022:22'

  docker:
    container_name: dind
    image: docker:dind
    privileged: true
    networks: 
      - jenkinsnet
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./data/jenkins-docker-certs:/certs/client
      - ./data/jenkins-data:/var/jenkins_home
    expose:
      - "2376"

  jenkins:
    container_name: jenkins
    build: ./docker/jenkins
    depends_on:
      - docker
    networks: 
      - jenkinsnet
      - gitjenkinsnet
      - nginxnet
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    expose:
      - "8080"
      - "50000"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins-docker-certs:/certs/client:ro
      - ./data/jenkins-data:/var/jenkins_home
    entrypoint:
      # - sh
      # - -c
      # - 'git config --global --add safe.directory "*"'
      # - --
      - /bin/tini
      - --
      - /usr/local/bin/jenkins.sh
